import Foundation
import OSLog

private let exportLogger = Logger(subsystem: "com.hadger.pith", category: "Exporter")

// MARK: - ExportEntryJSON

private struct ExportEntryJSON: Codable {
    let id: String
    let createdAt: String
    let durationSeconds: TimeInterval
    let title: String?
    let transcript: String
    let summary: String?
    let tags: [String]
    let audioFilename: String
}

// MARK: - ExportError

enum ExportError: Error, LocalizedError {
    case archiveFailed(underlying: Error)
    case noEntries

    var errorDescription: String? {
        switch self {
        case .archiveFailed(let underlying):
            "Couldn't assemble the export: \(underlying.localizedDescription)"
        case .noEntries:
            "There are no entries to export yet."
        }
    }
}

// MARK: - Exporter

/// FR-15 — assembles `entries.json` + `audio/*.m4a` + `README.md` into a
/// ZIP for the iOS share sheet.
///
/// No third-party ZIP dependency (honours FR-37 and SPEC § Technical
/// decisions). Uses `NSFileCoordinator.coordinate(readingItemAt:options:)`
/// with `.forUploading` — the system automatically ZIPs directory trees in
/// that mode.
@MainActor
enum Exporter {
    static func makeArchive(entries: [Entry]) async throws -> URL {
        guard !entries.isEmpty else { throw ExportError.noEntries }

        let fileManager = FileManager.default
        let staging = fileManager.temporaryDirectory
            .appendingPathComponent("pith-export-\(timestamp())", isDirectory: true)
        try? fileManager.removeItem(at: staging)
        try fileManager.createDirectory(at: staging, withIntermediateDirectories: true)
        let audioDir = staging.appendingPathComponent("audio", isDirectory: true)
        try fileManager.createDirectory(at: audioDir, withIntermediateDirectories: true)

        let formatter = ISO8601DateFormatter()
        let jsonModels = entries.map { entry in
            ExportEntryJSON(
                id: entry.id.uuidString,
                createdAt: formatter.string(from: entry.createdAt),
                durationSeconds: entry.duration,
                title: entry.userTitle,
                transcript: entry.transcript,
                summary: entry.summary,
                tags: entry.tags,
                audioFilename: entry.audioFilename
            )
        }
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let jsonData = try encoder.encode(jsonModels)
        try jsonData.write(to: staging.appendingPathComponent("entries.json"))

        for entry in entries {
            guard let src = entry.audioURL,
                  fileManager.fileExists(atPath: src.path) else { continue }
            let dst = audioDir.appendingPathComponent(entry.audioFilename)
            try? fileManager.copyItem(at: src, to: dst)
        }

        let readme = """
        # Pith export

        This archive is a copy of the entries you created in Pith Voice on
        your iPhone. Pith Voice does not keep a server-side record.

        ## Contents

        - `entries.json` — chronological list of entries with transcripts,
          summaries, themes, and timestamps (ISO 8601, UTC).
        - `audio/` — one `.m4a` per entry, named by entry ID. The
          `audioFilename` field in `entries.json` maps each entry to its file.
        - This README.

        Generated by Pith Voice on \(Date()).
        """
        try Data(readme.utf8).write(to: staging.appendingPathComponent("README.md"))

        return try await coordinatedZip(stagingDir: staging)
    }

    private static func coordinatedZip(stagingDir: URL) async throws -> URL {
        try await withCheckedThrowingContinuation { (cont: CheckedContinuation<URL, Error>) in
            let coordinator = NSFileCoordinator()
            var coordinationError: NSError?
            coordinator.coordinate(
                readingItemAt: stagingDir,
                options: [.forUploading],
                error: &coordinationError
            ) { tmpZip in
                do {
                    let fileManager = FileManager.default
                    let finalURL = fileManager.temporaryDirectory
                        .appendingPathComponent("\(stagingDir.lastPathComponent).zip")
                    try? fileManager.removeItem(at: finalURL)
                    try fileManager.copyItem(at: tmpZip, to: finalURL)
                    cont.resume(returning: finalURL)
                } catch {
                    cont.resume(throwing: ExportError.archiveFailed(underlying: error))
                }
            }
            if let coordinationError {
                cont.resume(throwing: ExportError.archiveFailed(underlying: coordinationError))
            }
        }
    }

    nonisolated static func timestamp(_ now: Date = Date()) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd-HHmmss"
        formatter.locale = Locale(identifier: "en_US_POSIX")
        return formatter.string(from: now)
    }
}
